name: DADA-SR1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=21.2
  - pytorch=1.10
  - torchvision=0.11
  - cudatoolkit=11.6
  - h5py=3.3
  - ruamel.yaml
  - scikit-image=0.18
  - scipy=1.6.2
  - pip:
    - setuptools==59.5.0
    - configargparse==1.5.3
    - segmentation-models-pytorch==0.2
    - tqdm
